--------------------------------------------------------
--  File created - Saturday-March-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "JEGY" 
   (	"ID" NUMBER, 
	"FELHASZNALO" VARCHAR2(20 BYTE), 
	"UT" NUMBER, 
	"KOCSI" NUMBER, 
	"SZEK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZEK
--------------------------------------------------------

  CREATE TABLE "SZEK" 
   (	"ID" NUMBER, 
	"TIPUS" VARCHAR2(20 BYTE), 
	"ASZTAL" NUMBER(1,0), 
	"ABLAK" NUMBER(1,0), 
	"MELLETTE_LEVO_SZEK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SZEK"."ASZTAL" IS 'boolean';
 
   COMMENT ON COLUMN "SZEK"."ABLAK" IS 'boolean';
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "ALLOMAS" 
   (	"ID" NUMBER, 
	"NEVE" VARCHAR2(30 BYTE), 
	"PERON_SZAM" NUMBER, 
	"KAVEZO" NUMBER(1,0), 
	"JEGYPENZTAR" NUMBER(1,0), 
	"INFO_PONT" NUMBER(1,0), 
	"WIFI" NUMBER(1,0), 
	"MOZGASKORLATOZOTT_ELERES" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "ALLOMAS"."KAVEZO" IS 'boolean';
 
   COMMENT ON COLUMN "ALLOMAS"."JEGYPENZTAR" IS 'boolean';
 
   COMMENT ON COLUMN "ALLOMAS"."INFO_PONT" IS 'boolean';
 
   COMMENT ON COLUMN "ALLOMAS"."WIFI" IS 'boolean';
 
   COMMENT ON COLUMN "ALLOMAS"."MOZGASKORLATOZOTT_ELERES" IS 'boolean';
--------------------------------------------------------
--  DDL for Table MOZDONY
--------------------------------------------------------

  CREATE TABLE "MOZDONY" 
   (	"ID" NUMBER, 
	"GYARTASI_EV" DATE, 
	"TIPUS" VARCHAR2(20 BYTE), 
	"UZEMANYAG" VARCHAR2(20 BYTE), 
	"HUZOERO" BINARY_FLOAT, 
	"SEBESSEG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FELHASZNALO
--------------------------------------------------------

  CREATE TABLE "FELHASZNALO" 
   (	"FELHASZNALONEV" VARCHAR2(30 BYTE), 
	"SZULETESI_DATUM" DATE, 
	"TELJES_NEV" VARCHAR2(50 BYTE), 
	"BANKKARTYA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  CREATE TABLE "ALLOMAS_DOLGOZO" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"ALLOMAS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENETREND
--------------------------------------------------------

  CREATE TABLE "MENETREND" 
   (	"ID" NUMBER, 
	"ISMETLODES_TIPUSA" NUMBER, 
	"NEV" VARCHAR2(20 BYTE), 
	"INDULASI_IDO" TIMESTAMP (6), 
	"HET_NAPJA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOLGOZO
--------------------------------------------------------

  CREATE TABLE "DOLGOZO" 
   (	"ID" NUMBER, 
	"NEV" VARCHAR2(60 BYTE), 
	"SZULETESI_DATUM" DATE, 
	"ADOSZAM" NUMBER, 
	"BEOSZTAS" VARCHAR2(40 BYTE), 
	"LAKCIM" VARCHAR2(60 BYTE), 
	"FIZETESE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KALAUZ
--------------------------------------------------------

  CREATE TABLE "KALAUZ" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"UT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEGALLO
--------------------------------------------------------

  CREATE TABLE "MEGALLO" 
   (	"ID" NUMBER, 
	"ALLOMAS" NUMBER, 
	"JARAT" NUMBER, 
	"IDO" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZABADSAG
--------------------------------------------------------

  CREATE TABLE "SZABADSAG" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"KEZDETE" DATE, 
	"VEGE" DATE, 
	"JOVAHAGYOTT" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SZABADSAG"."JOVAHAGYOTT" IS 'boolean';
--------------------------------------------------------
--  DDL for Table KOCSI
--------------------------------------------------------

  CREATE TABLE "KOCSI" 
   (	"ID" NUMBER, 
	"FEROHELY" NUMBER, 
	"TIPUS" VARCHAR2(40 BYTE), 
	"KONNEKTOR" NUMBER(1,0), 
	"WIFI" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "KOCSI"."KONNEKTOR" IS 'boolean';
 
   COMMENT ON COLUMN "KOCSI"."WIFI" IS 'boolean';
--------------------------------------------------------
--  DDL for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  CREATE TABLE "SZERELVENY_KOCSIK" 
   (	"ID" NUMBER, 
	"SZERELVENY" NUMBER, 
	"KOCSI" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "SZERELVENY" 
   (	"ID" NUMBER, 
	"MOZDONY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTAK
--------------------------------------------------------

  CREATE TABLE "UTAK" 
   (	"ID" NUMBER, 
	"MENETREND" NUMBER, 
	"IDO" DATE, 
	"SZERELVENY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into H881180.JEGY
SET DEFINE OFF;
REM INSERTING into H881180.SZEK
SET DEFINE OFF;
REM INSERTING into H881180.ALLOMAS
SET DEFINE OFF;
REM INSERTING into H881180.MOZDONY
SET DEFINE OFF;
REM INSERTING into H881180.FELHASZNALO
SET DEFINE OFF;
REM INSERTING into H881180.ALLOMAS_DOLGOZO
SET DEFINE OFF;
REM INSERTING into H881180.MENETREND
SET DEFINE OFF;
REM INSERTING into H881180.DOLGOZO
SET DEFINE OFF;
REM INSERTING into H881180.KALAUZ
SET DEFINE OFF;
REM INSERTING into H881180.MEGALLO
SET DEFINE OFF;
REM INSERTING into H881180.SZABADSAG
SET DEFINE OFF;
REM INSERTING into H881180.KOCSI
SET DEFINE OFF;
REM INSERTING into H881180.SZERELVENY_KOCSIK
SET DEFINE OFF;
REM INSERTING into H881180.SZERELVENY
SET DEFINE OFF;
REM INSERTING into H881180.UTAK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index JEGY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "JEGY_ID" ON "JEGY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZEK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZEK_ID" ON "SZEK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALLOMAS_ID" ON "ALLOMAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOZDONY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOZDONY_ID" ON "MOZDONY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FELHASZNALO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "FELHASZNALO_ID" ON "FELHASZNALO" ("FELHASZNALONEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_DOLGOZO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALLOMAS_DOLGOZO_ID" ON "ALLOMAS_DOLGOZO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENETREND_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MENETREND_ID" ON "MENETREND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOLGOZO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOLGOZO_ID" ON "DOLGOZO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KALAUZ_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "KALAUZ_ID" ON "KALAUZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEGALLO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEGALLO_ID" ON "MEGALLO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZABADSAG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABADSAG_ID" ON "SZABADSAG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KOCSI_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "KOCSI_ID" ON "KOCSI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_KOCSIK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZERELVENY_KOCSIK_ID" ON "SZERELVENY_KOCSIK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZERELVENY_ID" ON "SZERELVENY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UTAK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTAK_ID" ON "UTAK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "JEGY" ADD CONSTRAINT "JEGY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JEGY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "JEGY" MODIFY ("FELHASZNALO" NOT NULL ENABLE);
 
  ALTER TABLE "JEGY" MODIFY ("UT" NOT NULL ENABLE);
 
  ALTER TABLE "JEGY" MODIFY ("KOCSI" NOT NULL ENABLE);
 
  ALTER TABLE "JEGY" MODIFY ("SZEK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZEK
--------------------------------------------------------

  ALTER TABLE "SZEK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SZEK" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "SZEK" MODIFY ("ASZTAL" NOT NULL ENABLE);
 
  ALTER TABLE "SZEK" MODIFY ("ABLAK" NOT NULL ENABLE);
 
  ALTER TABLE "SZEK" MODIFY ("MELLETTE_LEVO_SZEK" NOT NULL ENABLE);
 
  ALTER TABLE "SZEK" ADD CONSTRAINT "SZEK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "ALLOMAS" ADD CONSTRAINT "ALLOMAS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALLOMAS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("NEVE" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("PERON_SZAM" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("KAVEZO" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("JEGYPENZTAR" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("INFO_PONT" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("WIFI" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS" MODIFY ("MOZGASKORLATOZOTT_ELERES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOZDONY
--------------------------------------------------------

  ALTER TABLE "MOZDONY" ADD CONSTRAINT "MOZDONY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MOZDONY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MOZDONY" MODIFY ("GYARTASI_EV" NOT NULL ENABLE);
 
  ALTER TABLE "MOZDONY" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "MOZDONY" MODIFY ("UZEMANYAG" NOT NULL ENABLE);
 
  ALTER TABLE "MOZDONY" MODIFY ("SEBESSEG" NOT NULL ENABLE);
 
  ALTER TABLE "MOZDONY" MODIFY ("HUZOERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FELHASZNALO
--------------------------------------------------------

  ALTER TABLE "FELHASZNALO" ADD CONSTRAINT "FELHASZNALO_ID" PRIMARY KEY ("FELHASZNALONEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FELHASZNALO" MODIFY ("SZULETESI_DATUM" NOT NULL ENABLE);
 
  ALTER TABLE "FELHASZNALO" MODIFY ("TELJES_NEV" NOT NULL ENABLE);
 
  ALTER TABLE "FELHASZNALO" MODIFY ("FELHASZNALONEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  ALTER TABLE "ALLOMAS_DOLGOZO" ADD CONSTRAINT "ALLOMAS_DOLGOZO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ALLOMAS_DOLGOZO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS_DOLGOZO" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "ALLOMAS_DOLGOZO" MODIFY ("ALLOMAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENETREND
--------------------------------------------------------

  ALTER TABLE "MENETREND" ADD CONSTRAINT "MENETREND_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MENETREND" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MENETREND" MODIFY ("ISMETLODES_TIPUSA" NOT NULL ENABLE);
 
  ALTER TABLE "MENETREND" MODIFY ("NEV" NOT NULL ENABLE);
 
  ALTER TABLE "MENETREND" MODIFY ("INDULASI_IDO" NOT NULL ENABLE);
 
  ALTER TABLE "MENETREND" MODIFY ("HET_NAPJA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOLGOZO
--------------------------------------------------------

  ALTER TABLE "DOLGOZO" ADD CONSTRAINT "DOLGOZO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOLGOZO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("NEV" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("SZULETESI_DATUM" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("ADOSZAM" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("BEOSZTAS" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("LAKCIM" NOT NULL ENABLE);
 
  ALTER TABLE "DOLGOZO" MODIFY ("FIZETESE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KALAUZ
--------------------------------------------------------

  ALTER TABLE "KALAUZ" ADD CONSTRAINT "KALAUZ_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KALAUZ" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "KALAUZ" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "KALAUZ" MODIFY ("UT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEGALLO
--------------------------------------------------------

  ALTER TABLE "MEGALLO" ADD CONSTRAINT "MEGALLO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MEGALLO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MEGALLO" MODIFY ("ALLOMAS" NOT NULL ENABLE);
 
  ALTER TABLE "MEGALLO" MODIFY ("JARAT" NOT NULL ENABLE);
 
  ALTER TABLE "MEGALLO" MODIFY ("IDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZABADSAG
--------------------------------------------------------

  ALTER TABLE "SZABADSAG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SZABADSAG" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "SZABADSAG" MODIFY ("KEZDETE" NOT NULL ENABLE);
 
  ALTER TABLE "SZABADSAG" MODIFY ("VEGE" NOT NULL ENABLE);
 
  ALTER TABLE "SZABADSAG" MODIFY ("JOVAHAGYOTT" NOT NULL ENABLE);
 
  ALTER TABLE "SZABADSAG" ADD CONSTRAINT "SZABADSAG_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOCSI
--------------------------------------------------------

  ALTER TABLE "KOCSI" ADD CONSTRAINT "KOCSI_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KOCSI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "KOCSI" MODIFY ("FEROHELY" NOT NULL ENABLE);
 
  ALTER TABLE "KOCSI" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "KOCSI" MODIFY ("KONNEKTOR" NOT NULL ENABLE);
 
  ALTER TABLE "KOCSI" MODIFY ("WIFI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  ALTER TABLE "SZERELVENY_KOCSIK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SZERELVENY_KOCSIK" MODIFY ("SZERELVENY" NOT NULL ENABLE);
 
  ALTER TABLE "SZERELVENY_KOCSIK" MODIFY ("KOCSI" NOT NULL ENABLE);
 
  ALTER TABLE "SZERELVENY_KOCSIK" ADD CONSTRAINT "SZERELVENY_KOCSIK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "SZERELVENY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SZERELVENY" MODIFY ("MOZDONY" NOT NULL ENABLE);
 
  ALTER TABLE "SZERELVENY" ADD CONSTRAINT "SZERELVENY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTAK
--------------------------------------------------------

  ALTER TABLE "UTAK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "UTAK" MODIFY ("MENETREND" NOT NULL ENABLE);
 
  ALTER TABLE "UTAK" MODIFY ("IDO" NOT NULL ENABLE);
 
  ALTER TABLE "UTAK" MODIFY ("SZERELVENY" NOT NULL ENABLE);
 
  ALTER TABLE "UTAK" ADD CONSTRAINT "UTAK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "JEGY" ADD CONSTRAINT "FK_JEGY_FELHASZNALO" FOREIGN KEY ("FELHASZNALO")
	  REFERENCES "FELHASZNALO" ("FELHASZNALONEV") ENABLE;
 
  ALTER TABLE "JEGY" ADD CONSTRAINT "FK_JEGY_KOCSI" FOREIGN KEY ("KOCSI")
	  REFERENCES "KOCSI" ("ID") ENABLE;
 
  ALTER TABLE "JEGY" ADD CONSTRAINT "FK_JEGY_SZEK" FOREIGN KEY ("SZEK")
	  REFERENCES "SZEK" ("ID") ENABLE;
 
  ALTER TABLE "JEGY" ADD CONSTRAINT "FK_JEGY_UT_ID" FOREIGN KEY ("UT")
	  REFERENCES "UTAK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZEK
--------------------------------------------------------

  ALTER TABLE "SZEK" ADD CONSTRAINT "MELLETTE_LEVO_SZEK_ID" FOREIGN KEY ("MELLETTE_LEVO_SZEK")
	  REFERENCES "SZEK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  ALTER TABLE "ALLOMAS_DOLGOZO" ADD CONSTRAINT "FK_ALLOMAS_DOLGOZO_ALLOMAS_ID" FOREIGN KEY ("ALLOMAS")
	  REFERENCES "ALLOMAS" ("ID") ENABLE;
 
  ALTER TABLE "ALLOMAS_DOLGOZO" ADD CONSTRAINT "FK_ALLOMAS_DOLGOZO_DOLGOZO_ID" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "DOLGOZO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KALAUZ
--------------------------------------------------------

  ALTER TABLE "KALAUZ" ADD CONSTRAINT "FK_KALAUZ_DOLGOZO" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "DOLGOZO" ("ID") ENABLE;
 
  ALTER TABLE "KALAUZ" ADD CONSTRAINT "FK_KALAUZ_UT_ID" FOREIGN KEY ("UT")
	  REFERENCES "UTAK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEGALLO
--------------------------------------------------------

  ALTER TABLE "MEGALLO" ADD CONSTRAINT "FK_MEGALLO_ALLOMAS_ID" FOREIGN KEY ("ALLOMAS")
	  REFERENCES "ALLOMAS" ("ID") ENABLE;
 
  ALTER TABLE "MEGALLO" ADD CONSTRAINT "FK_MENETREND_JARAT_ID" FOREIGN KEY ("JARAT")
	  REFERENCES "MENETREND" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZABADSAG
--------------------------------------------------------

  ALTER TABLE "SZABADSAG" ADD CONSTRAINT "FK_SZABADSAG_DOLGOZO" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "DOLGOZO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  ALTER TABLE "SZERELVENY_KOCSIK" ADD CONSTRAINT "FK_SZERELVENYKOCSIK_KOCSI" FOREIGN KEY ("KOCSI")
	  REFERENCES "KOCSI" ("ID") ENABLE;
 
  ALTER TABLE "SZERELVENY_KOCSIK" ADD CONSTRAINT "FK_SZERELVENYKOCSIK_SZERELVENY" FOREIGN KEY ("SZERELVENY")
	  REFERENCES "SZERELVENY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "SZERELVENY" ADD CONSTRAINT "FK_SZERELVENY_MOZDONY_ID" FOREIGN KEY ("MOZDONY")
	  REFERENCES "MOZDONY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTAK
--------------------------------------------------------

  ALTER TABLE "UTAK" ADD CONSTRAINT "FK_UTAK_MENETREND_ID" FOREIGN KEY ("MENETREND")
	  REFERENCES "MENETREND" ("ID") ENABLE;
 
  ALTER TABLE "UTAK" ADD CONSTRAINT "FK_UTAK_SZERELVENY" FOREIGN KEY ("SZERELVENY")
	  REFERENCES "SZERELVENY" ("ID") ENABLE;
