--------------------------------------------------------
--  File created - Saturday-March-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALLOMAS
--------------------------------------------------------

  CREATE TABLE "H881180"."ALLOMAS" 
   (	"ID" NUMBER, 
	"NEVE" VARCHAR2(30 BYTE), 
	"PERON_SZAM" NUMBER, 
	"KAVEZO" NUMBER(1,0), 
	"JEGYPENZTAR" NUMBER(1,0), 
	"INFO_PONT" NUMBER(1,0), 
	"WIFI" NUMBER(1,0), 
	"MOZGASKORLATOZOTT_ELERES" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "H881180"."ALLOMAS"."KAVEZO" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."ALLOMAS"."JEGYPENZTAR" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."ALLOMAS"."INFO_PONT" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."ALLOMAS"."WIFI" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."ALLOMAS"."MOZGASKORLATOZOTT_ELERES" IS 'boolean';
--------------------------------------------------------
--  DDL for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  CREATE TABLE "H881180"."ALLOMAS_DOLGOZO" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"ALLOMAS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "H881180"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOLGOZO
--------------------------------------------------------

  CREATE TABLE "H881180"."DOLGOZO" 
   (	"ID" NUMBER, 
	"NEV" VARCHAR2(60 BYTE), 
	"SZULETESI_DATUM" DATE, 
	"ADOSZAM" NUMBER, 
	"BEOSZTAS" VARCHAR2(40 BYTE), 
	"LAKCIM" VARCHAR2(60 BYTE), 
	"FIZETESE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "H881180"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FELHASZNALO
--------------------------------------------------------

  CREATE TABLE "H881180"."FELHASZNALO" 
   (	"FELHASZNALONEV" VARCHAR2(30 BYTE), 
	"SZULETESI_DATUM" DATE, 
	"TELJES_NEV" VARCHAR2(50 BYTE), 
	"BANKKARTYA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEGY
--------------------------------------------------------

  CREATE TABLE "H881180"."JEGY" 
   (	"ID" NUMBER, 
	"FELHASZNALO" VARCHAR2(20 BYTE), 
	"UT" NUMBER, 
	"KOCSI" NUMBER, 
	"SZEK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KALAUZ
--------------------------------------------------------

  CREATE TABLE "H881180"."KALAUZ" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"UT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOCSI
--------------------------------------------------------

  CREATE TABLE "H881180"."KOCSI" 
   (	"ID" NUMBER, 
	"FEROHELY" NUMBER, 
	"TIPUS" VARCHAR2(40 BYTE), 
	"KONNEKTOR" NUMBER(1,0), 
	"WIFI" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "H881180"."KOCSI"."KONNEKTOR" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."KOCSI"."WIFI" IS 'boolean';
--------------------------------------------------------
--  DDL for Table MEGALLO
--------------------------------------------------------

  CREATE TABLE "H881180"."MEGALLO" 
   (	"ID" NUMBER, 
	"ALLOMAS" NUMBER, 
	"JARAT" NUMBER, 
	"IDO" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENETREND
--------------------------------------------------------

  CREATE TABLE "H881180"."MENETREND" 
   (	"ID" NUMBER, 
	"ISMETLODES_TIPUSA" NUMBER, 
	"NEV" VARCHAR2(20 BYTE), 
	"INDULASI_IDO" TIMESTAMP (6), 
	"HET_NAPJA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOZDONY
--------------------------------------------------------

  CREATE TABLE "H881180"."MOZDONY" 
   (	"ID" NUMBER, 
	"GYARTASI_EV" DATE, 
	"TIPUS" VARCHAR2(20 BYTE), 
	"UZEMANYAG" VARCHAR2(20 BYTE), 
	"HUZOERO" BINARY_FLOAT, 
	"SEBESSEG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZABADSAG
--------------------------------------------------------

  CREATE TABLE "H881180"."SZABADSAG" 
   (	"ID" NUMBER, 
	"DOLGOZO" NUMBER, 
	"KEZDETE" DATE, 
	"VEGE" DATE, 
	"JOVAHAGYOTT" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "H881180"."SZABADSAG"."JOVAHAGYOTT" IS 'boolean';
--------------------------------------------------------
--  DDL for Table SZEK
--------------------------------------------------------

  CREATE TABLE "H881180"."SZEK" 
   (	"ID" NUMBER, 
	"TIPUS" VARCHAR2(20 BYTE), 
	"ASZTAL" NUMBER(1,0), 
	"ABLAK" NUMBER(1,0), 
	"MELLETTE_LEVO_SZEK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "H881180"."SZEK"."ASZTAL" IS 'boolean';
 
   COMMENT ON COLUMN "H881180"."SZEK"."ABLAK" IS 'boolean';
--------------------------------------------------------
--  DDL for Table SZERELVENY
--------------------------------------------------------

  CREATE TABLE "H881180"."SZERELVENY" 
   (	"ID" NUMBER, 
	"MOZDONY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  CREATE TABLE "H881180"."SZERELVENY_KOCSIK" 
   (	"ID" NUMBER, 
	"SZERELVENY" NUMBER, 
	"KOCSI" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTAK
--------------------------------------------------------

  CREATE TABLE "H881180"."UTAK" 
   (	"ID" NUMBER, 
	"MENETREND" NUMBER, 
	"IDO" DATE, 
	"SZERELVENY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into H881180.ALLOMAS
SET DEFINE OFF;
REM INSERTING into H881180.ALLOMAS_DOLGOZO
SET DEFINE OFF;
REM INSERTING into H881180.DEPT
SET DEFINE OFF;
Insert into H881180.DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTING','NEW YORK');
Insert into H881180.DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCH','DALLAS');
Insert into H881180.DEPT (DEPTNO,DNAME,LOC) values (30,'SALES','CHICAGO');
Insert into H881180.DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONS','BOSTON');
REM INSERTING into H881180.DOLGOZO
SET DEFINE OFF;
REM INSERTING into H881180.EMP
SET DEFINE OFF;
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7839,'KING','PRESIDENT',null,to_date('17-NOV-81','DD-MON-RR'),5000,null,10);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7698,'BLAKE','MANAGER',7839,to_date('01-MAY-81','DD-MON-RR'),2850,null,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7782,'CLARK','MANAGER',7839,to_date('09-JUN-81','DD-MON-RR'),2450,null,10);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7566,'JONES','MANAGER',7839,to_date('02-APR-81','DD-MON-RR'),2975,null,20);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7654,'MARTIN','SALESMAN',7698,to_date('28-SEP-81','DD-MON-RR'),1250,1400,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7499,'ALLEN','SALESMAN',7698,to_date('20-FEB-81','DD-MON-RR'),1600,300,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7844,'TURNER','SALESMAN',7698,to_date('08-SEP-81','DD-MON-RR'),1500,0,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7900,'JAMES','CLERK',7698,to_date('03-DEC-81','DD-MON-RR'),950,null,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7521,'WARD','SALESMAN',7698,to_date('22-FEB-81','DD-MON-RR'),1250,500,30);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7902,'FORD','ANALYST',7566,to_date('03-DEC-81','DD-MON-RR'),3000,null,20);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7369,'SMITH','CLERK',7902,to_date('17-DEC-80','DD-MON-RR'),800,null,20);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7788,'SCOTT','ANALYST',7566,to_date('09-DEC-82','DD-MON-RR'),3000,null,20);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7876,'ADAMS','CLERK',7788,to_date('12-JAN-83','DD-MON-RR'),1100,null,20);
Insert into H881180.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7934,'MILLER','CLERK',7782,to_date('23-JAN-82','DD-MON-RR'),1300,null,10);
REM INSERTING into H881180.FELHASZNALO
SET DEFINE OFF;
REM INSERTING into H881180.JEGY
SET DEFINE OFF;
REM INSERTING into H881180.KALAUZ
SET DEFINE OFF;
REM INSERTING into H881180.KOCSI
SET DEFINE OFF;
REM INSERTING into H881180.MEGALLO
SET DEFINE OFF;
REM INSERTING into H881180.MENETREND
SET DEFINE OFF;
REM INSERTING into H881180.MOZDONY
SET DEFINE OFF;
REM INSERTING into H881180.SZABADSAG
SET DEFINE OFF;
REM INSERTING into H881180.SZEK
SET DEFINE OFF;
REM INSERTING into H881180.SZERELVENY
SET DEFINE OFF;
REM INSERTING into H881180.SZERELVENY_KOCSIK
SET DEFINE OFF;
REM INSERTING into H881180.UTAK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index KOCSI_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."KOCSI_ID" ON "H881180"."KOCSI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_DOLGOZO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."ALLOMAS_DOLGOZO_ID" ON "H881180"."ALLOMAS_DOLGOZO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENETREND_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."MENETREND_ID" ON "H881180"."MENETREND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FELHASZNALO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."FELHASZNALO_ID" ON "H881180"."FELHASZNALO" ("FELHASZNALONEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOLGOZO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."DOLGOZO_ID" ON "H881180"."DOLGOZO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UTAK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."UTAK_ID" ON "H881180"."UTAK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPT_PRIMARY_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."DEPT_PRIMARY_KEY" ON "H881180"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOZDONY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."MOZDONY_ID" ON "H881180"."MOZDONY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JEGY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."JEGY_ID" ON "H881180"."JEGY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KALAUZ_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."KALAUZ_ID" ON "H881180"."KALAUZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZABADSAG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."SZABADSAG_ID" ON "H881180"."SZABADSAG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEGALLO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."MEGALLO_ID" ON "H881180"."MEGALLO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMP_PRIMARY_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."EMP_PRIMARY_KEY" ON "H881180"."EMP" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_KOCSIK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."SZERELVENY_KOCSIK_ID" ON "H881180"."SZERELVENY_KOCSIK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLOMAS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."ALLOMAS_ID" ON "H881180"."ALLOMAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZEK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."SZEK_ID" ON "H881180"."SZEK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SZERELVENY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "H881180"."SZERELVENY_ID" ON "H881180"."SZERELVENY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DOLGOZO
--------------------------------------------------------

  ALTER TABLE "H881180"."DOLGOZO" ADD CONSTRAINT "DOLGOZO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("NEV" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("SZULETESI_DATUM" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("ADOSZAM" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("BEOSZTAS" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("LAKCIM" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."DOLGOZO" MODIFY ("FIZETESE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "H881180"."JEGY" ADD CONSTRAINT "JEGY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."JEGY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."JEGY" MODIFY ("FELHASZNALO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."JEGY" MODIFY ("UT" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."JEGY" MODIFY ("KOCSI" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."JEGY" MODIFY ("SZEK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENETREND
--------------------------------------------------------

  ALTER TABLE "H881180"."MENETREND" ADD CONSTRAINT "MENETREND_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."MENETREND" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MENETREND" MODIFY ("ISMETLODES_TIPUSA" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MENETREND" MODIFY ("NEV" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MENETREND" MODIFY ("INDULASI_IDO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MENETREND" MODIFY ("HET_NAPJA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KALAUZ
--------------------------------------------------------

  ALTER TABLE "H881180"."KALAUZ" ADD CONSTRAINT "KALAUZ_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."KALAUZ" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KALAUZ" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KALAUZ" MODIFY ("UT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "H881180"."DEPT" ADD CONSTRAINT "DEPT_PRIMARY_KEY" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."DEPT" MODIFY ("DEPTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KOCSI
--------------------------------------------------------

  ALTER TABLE "H881180"."KOCSI" ADD CONSTRAINT "KOCSI_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."KOCSI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KOCSI" MODIFY ("FEROHELY" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KOCSI" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KOCSI" MODIFY ("KONNEKTOR" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."KOCSI" MODIFY ("WIFI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEGALLO
--------------------------------------------------------

  ALTER TABLE "H881180"."MEGALLO" ADD CONSTRAINT "MEGALLO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."MEGALLO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MEGALLO" MODIFY ("ALLOMAS" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MEGALLO" MODIFY ("JARAT" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MEGALLO" MODIFY ("IDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" MODIFY ("SZERELVENY" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" MODIFY ("KOCSI" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" ADD CONSTRAINT "SZERELVENY_KOCSIK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SZEK
--------------------------------------------------------

  ALTER TABLE "H881180"."SZEK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZEK" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZEK" MODIFY ("ASZTAL" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZEK" MODIFY ("ABLAK" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZEK" MODIFY ("MELLETTE_LEVO_SZEK" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZEK" ADD CONSTRAINT "SZEK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "H881180"."SZERELVENY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZERELVENY" MODIFY ("MOZDONY" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZERELVENY" ADD CONSTRAINT "SZERELVENY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" ADD CONSTRAINT "ALLOMAS_DOLGOZO_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" MODIFY ("ALLOMAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTAK
--------------------------------------------------------

  ALTER TABLE "H881180"."UTAK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."UTAK" MODIFY ("MENETREND" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."UTAK" MODIFY ("IDO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."UTAK" MODIFY ("SZERELVENY" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."UTAK" ADD CONSTRAINT "UTAK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FELHASZNALO
--------------------------------------------------------

  ALTER TABLE "H881180"."FELHASZNALO" ADD CONSTRAINT "FELHASZNALO_ID" PRIMARY KEY ("FELHASZNALONEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."FELHASZNALO" MODIFY ("SZULETESI_DATUM" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."FELHASZNALO" MODIFY ("TELJES_NEV" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."FELHASZNALO" MODIFY ("FELHASZNALONEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOMAS
--------------------------------------------------------

  ALTER TABLE "H881180"."ALLOMAS" ADD CONSTRAINT "ALLOMAS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("NEVE" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("PERON_SZAM" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("KAVEZO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("JEGYPENZTAR" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("INFO_PONT" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("WIFI" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."ALLOMAS" MODIFY ("MOZGASKORLATOZOTT_ELERES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZABADSAG
--------------------------------------------------------

  ALTER TABLE "H881180"."SZABADSAG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZABADSAG" MODIFY ("DOLGOZO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZABADSAG" MODIFY ("KEZDETE" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZABADSAG" MODIFY ("VEGE" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZABADSAG" MODIFY ("JOVAHAGYOTT" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."SZABADSAG" ADD CONSTRAINT "SZABADSAG_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOZDONY
--------------------------------------------------------

  ALTER TABLE "H881180"."MOZDONY" ADD CONSTRAINT "MOZDONY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("GYARTASI_EV" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("TIPUS" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("UZEMANYAG" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("SEBESSEG" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."MOZDONY" MODIFY ("HUZOERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "H881180"."EMP" ADD CONSTRAINT "EMP_PRIMARY_KEY" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "H881180"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
 
  ALTER TABLE "H881180"."EMP" MODIFY ("DEPTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALLOMAS_DOLGOZO
--------------------------------------------------------

  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" ADD CONSTRAINT "FK_ALLOMAS_DOLGOZO_ALLOMAS_ID" FOREIGN KEY ("ALLOMAS")
	  REFERENCES "H881180"."ALLOMAS" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."ALLOMAS_DOLGOZO" ADD CONSTRAINT "FK_ALLOMAS_DOLGOZO_DOLGOZO_ID" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "H881180"."DOLGOZO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "H881180"."EMP" ADD CONSTRAINT "EMP_FOREIGN_KEY" FOREIGN KEY ("DEPTNO")
	  REFERENCES "H881180"."DEPT" ("DEPTNO") ENABLE;
 
  ALTER TABLE "H881180"."EMP" ADD CONSTRAINT "EMP_SELF_KEY" FOREIGN KEY ("MGR")
	  REFERENCES "H881180"."EMP" ("EMPNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEGY
--------------------------------------------------------

  ALTER TABLE "H881180"."JEGY" ADD CONSTRAINT "FK_JEGY_FELHASZNALO" FOREIGN KEY ("FELHASZNALO")
	  REFERENCES "H881180"."FELHASZNALO" ("FELHASZNALONEV") ENABLE;
 
  ALTER TABLE "H881180"."JEGY" ADD CONSTRAINT "FK_JEGY_KOCSI" FOREIGN KEY ("KOCSI")
	  REFERENCES "H881180"."KOCSI" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."JEGY" ADD CONSTRAINT "FK_JEGY_SZEK" FOREIGN KEY ("SZEK")
	  REFERENCES "H881180"."SZEK" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."JEGY" ADD CONSTRAINT "FK_JEGY_UT_ID" FOREIGN KEY ("UT")
	  REFERENCES "H881180"."UTAK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KALAUZ
--------------------------------------------------------

  ALTER TABLE "H881180"."KALAUZ" ADD CONSTRAINT "FK_KALAUZ_DOLGOZO" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "H881180"."DOLGOZO" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."KALAUZ" ADD CONSTRAINT "FK_KALAUZ_UT_ID" FOREIGN KEY ("UT")
	  REFERENCES "H881180"."UTAK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEGALLO
--------------------------------------------------------

  ALTER TABLE "H881180"."MEGALLO" ADD CONSTRAINT "FK_MEGALLO_ALLOMAS_ID" FOREIGN KEY ("ALLOMAS")
	  REFERENCES "H881180"."ALLOMAS" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."MEGALLO" ADD CONSTRAINT "FK_MENETREND_JARAT_ID" FOREIGN KEY ("JARAT")
	  REFERENCES "H881180"."MENETREND" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZABADSAG
--------------------------------------------------------

  ALTER TABLE "H881180"."SZABADSAG" ADD CONSTRAINT "FK_SZABADSAG_DOLGOZO" FOREIGN KEY ("DOLGOZO")
	  REFERENCES "H881180"."DOLGOZO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZEK
--------------------------------------------------------

  ALTER TABLE "H881180"."SZEK" ADD CONSTRAINT "MELLETTE_LEVO_SZEK_ID" FOREIGN KEY ("MELLETTE_LEVO_SZEK")
	  REFERENCES "H881180"."SZEK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZERELVENY
--------------------------------------------------------

  ALTER TABLE "H881180"."SZERELVENY" ADD CONSTRAINT "FK_SZERELVENY_MOZDONY_ID" FOREIGN KEY ("MOZDONY")
	  REFERENCES "H881180"."MOZDONY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZERELVENY_KOCSIK
--------------------------------------------------------

  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" ADD CONSTRAINT "FK_SZERELVENYKOCSIK_KOCSI" FOREIGN KEY ("KOCSI")
	  REFERENCES "H881180"."KOCSI" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."SZERELVENY_KOCSIK" ADD CONSTRAINT "FK_SZERELVENYKOCSIK_SZERELVENY" FOREIGN KEY ("SZERELVENY")
	  REFERENCES "H881180"."SZERELVENY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTAK
--------------------------------------------------------

  ALTER TABLE "H881180"."UTAK" ADD CONSTRAINT "FK_UTAK_MENETREND_ID" FOREIGN KEY ("MENETREND")
	  REFERENCES "H881180"."MENETREND" ("ID") ENABLE;
 
  ALTER TABLE "H881180"."UTAK" ADD CONSTRAINT "FK_UTAK_SZERELVENY" FOREIGN KEY ("SZERELVENY")
	  REFERENCES "H881180"."SZERELVENY" ("ID") ENABLE;
